[versions]
agp = "9.0.1"
coreKtx = "1.17.0"
leanback = "1.2.0"
glide = "5.0.5"
nextcloud-android-library = "2.22.1"
composeBom = "2026.02.00"
coilCompose = "2.7.0"
composeActivity = "1.12.4"
composeTv = "1.0.0-alpha12"
composeTvMaterial = "1.0.1"
composeNavigation = "2.9.7"
composeMaterial3 = "1.4.0"
kotlin = "2.3.10"
ktor="3.4.0"
kotlinx-coroutines = "1.10.2"
kotlintest = "3.4.2"
logback = "1.5.29"
zxing = "3.5.4"
slf4j = "2.0.17"
koin = "4.0.0"
security-crypto = "1.1.0-alpha06"
lifecycle = "2.8.7"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
nextcloud-android-library = { group = "com.github.nextcloud", name = "android-library", version.ref = "nextcloud-android-library" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }

# Compose dependencies
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }

compose-tv-foundation = { group = "androidx.tv", name = "tv-foundation", version.ref = "composeTv" }
compose-tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "composeTvMaterial" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-serialization-xml = { module = "io.ktor:ktor-serialization-kotlinx-xml", version.ref = "ktor" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.10.0" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

kotlintest-runner-junit5 = { module = "io.kotlintest:kotlintest-runner-junit5", version.ref = "kotlintest" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }

security-crypto = { module = "androidx.security:security-crypto", version.ref = "security-crypto" }

lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

