[versions]
agp = "8.13.2"
coreKtx = "1.17.0"
leanback = "1.2.0"
glide = "5.0.5"
nextcloud-android-library = "2.22.1"
composeBom = "2026.01.01"
coilCompose = "2.7.0"
composeActivity = "1.12.3"
composeTv = "1.0.0-alpha12"
composeTvMaterial = "1.0.1"
composeNavigation = "2.9.7"
composeMaterial3 = "1.4.0"
kotlin = "2.3.10"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
nextcloud-android-library = { group = "com.github.nextcloud", name = "android-library", version.ref = "nextcloud-android-library" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }

# Compose dependencies
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }

compose-tv-foundation = { group = "androidx.tv", name = "tv-foundation", version.ref = "composeTv" }
compose-tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "composeTvMaterial" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

