[versions]
agp = "9.0.0"
coreKtx = "1.10.1"
leanback = "1.0.0"
glide = "4.11.0"
nextcloud-android-library = "2.22.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
nextcloud-android-library = { group = "com.github.nextcloud", name = "android-library", version.ref = "nextcloud-android-library" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

